name: CI
on:
  push:
  pull_request:
jobs:
  wasi:
    runs-on: ubuntu-latest
    env:
      GHC_WASM_META_REV: 5a5c10c3b7e2f9f55bb2f40601cb20c9eb599bb5
      FLAVOUR: '9.6'
    steps:
    - name: Setup WASI GHC
      run: |
        cd $(mktemp -d)
        curl -L --retry 5 https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/archive/$GHC_WASM_META_REV/ghc-wasm-meta-master.tar.gz | tar xz --strip-components=1
        ./setup.sh
        ~/.ghc-wasm/add_to_github_path.sh
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.ghc-wasm/.cabal/store
          dist-newstyle
        key: build-wasi-${{ runner.os }}-wasm-meta-${{ env.GHC_WASM_META_REV }}-flavour-${{ env.FLAVOUR }}-${{ github.sha }}
        restore-keys: |
          build-wasi-${{ runner.os }}-wasm-meta-${{ env.GHC_WASM_META_REV }}-flavour-${{ env.FLAVOUR }}-

    - name: Build
      run: |
        wasm32-wasi-cabal build

  non-linux:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
        ghc: ['7.10.3', '8.0.2', '8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.7', '9.4.4', '9.6.1']

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - run: cabal build
    - run: cabal test --test-show-details=direct
